### ISSUE TITLE
sshpass

### ISSUE THREAD

**Issue by baffonso** [ownport/portable-ansible#9]
Hi,

Is it possible to include sshpass as part of the build?  

Thank you,

B

**Comment by ownport** [comment]
I'm not sure that I understood which sshpass you asked to add. The idea of portable ansible is to stay around python modules

**Comment by ownport** [comment]
as no comments for the issue, I will close it. Please re-open if the question is still actual and we continue discussion

**Comment by Voriaz** [comment]
Hello,

The problem is when you use a playbook, it may fail beacause sshpass is not install on the host.
See the Ansible error message below:
`fatal: [master]: FAILED! => {"msg": "to use the 'ssh' connection type with passwords, you must install the sshpass program"}`

So, is it possible to embed this package into the repo ? Beacause the idea is to use ansible without any installation.

Thanks,

A.

**Comment by ownport** [comment]
let me check

**Comment by ownport** [comment]
have you tried to use `-c paramiko` command line argument for ansible-playbook instead of ssh connection?

**Comment by berttejeda** [comment]
I managed to get this working as follows:

- Install the desired python package into a separate library folder named *extras*:
```bash
mkdir extras
pip install -t extras sshpass
```
- Place the extras folder inside the ansible folder:
```bash
mv extras ansible
```
- Add the following block to *ansible/__main__.py* (before *def clean_syspath*) so that we include this library folder in the python *sys.path*:
```python
if sys.platform in ['win32', 'cygwin']:
    project_root = os.path.dirname(os.path.abspath(__file__))
    sys.path.insert(0, project_root + '\\extras')
elif sys.platform in ['darwin']:
    project_root = os.path.dirname(os.path.abspath(__file__))
    sys.path.insert(0, project_root + '/extras')
else:
    project_root = os.path.dirname(os.path.abspath(__file__))
    sys.path.insert(0, project_root + '/extras')
```
Now your extra libraries are included in your portable ansible version.

**Comment by berttejeda** [comment]
> Hello,
> 
> The problem is when you use a playbook, it may fail beacause sshpass is not install on the host.
> See the Ansible error message below:
> `fatal: [master]: FAILED! => {"msg": "to use the 'ssh' connection type with passwords, you must install the sshpass program"}`
> 
> So, is it possible to embed this package into the repo ? Beacause the idea is to use ansible without any installation.
> 
> Thanks,
> 
> A.

I came across this stakoverflow post:
**ansible - to use the 'ssh' connection type with passwords, you must install the sshpass program" - Stack Overflow**: https://stackoverflow.com/questions/42835626/to-use-the-ssh-connection-type-with-passwords-you-must-install-the-sshpass-pr

Might be helpful.

**Comment by Voriaz** [comment]
Thanks, i will try your code

A.

**Comment by ownport** [comment]
There is option 
```
  -M MODULE_PATH, --module-path=MODULE_PATH
                        prepend colon-separated path(s) to module library
                        (default=['/home/ownport/.ansible/plugins/modules',
                        '/usr/share/ansible/plugins/modules'])
```
https://docs.ansible.com/ansible/latest/dev_guide/developing_locally.html

**Comment by berttejeda** [comment]
> There is option
> 
> ```
>   -M MODULE_PATH, --module-path=MODULE_PATH
>                         prepend colon-separated path(s) to module library
>                         (default=['/home/ownport/.ansible/plugins/modules',
>                         '/usr/share/ansible/plugins/modules'])
> ```
> https://docs.ansible.com/ansible/latest/dev_guide/developing_locally.html

That option only applies to your ansible run. It exposes any custom ansible modules you might have developed or acquired, and thus does not affect available python modules. 

Consider the following as an example:

You want to manage windows hosts using this portable distribution of ansible.

Apart from the appropriate system packages on your controller, you'll need the following python packages available to your portable ansible installation:

- kerberos
- pykerberos
- pywinrm
- requests-kerberos

If you have these listed in your requirements.txt, and you want to install them to ansible/extras -- you can accomplish this like so:

```bash
mkdir ansible/extras
pip install -t ansible/extras -r requirements.txt
```

In doing this and incorporating the changes I mentioned before (to ansible/\_\_main\_\_.py), you'd be able to manage windows hosts via winrm, with kerberos as your authentication mechanism.

**Comment by ownport** [comment]
thanks you so much @berttejeda for detail explanation. Pretty reasonable. The support of extras/ directory added in new release https://github.com/ownport/portable-ansible/releases/tag/v0.2.2

**Comment by ownport** [comment]
@Voriaz please let me know, if you still have questions

**Comment by ownport** [comment]
@Voriaz closing the case, please re-open if you have a questions.

**Comment by berttejeda** [comment]
I would be remiss not to mention this: 

Another route would be per-user site packages as described here: [PEP 370 -- Per user site-packages directory | Python.org](https://www.python.org/dev/peps/pep-0370/)

So instead of installing the stuff to ansible/extras, one could simply do as follows:

```bash
mkdir ${USER_SITE}
pip install -t ${USER_SITE} -r requirements.txt
```
You can determine your USER_BASE by running `python -m site`
e.g.

```
USER_BASE: '/home/myusername/.local' (exists)
USER_SITE: '/home/myusername/.local/lib/python2.7/site-packages' (exists)
```

**Comment by ownport** [comment]
I think it could be done in more simpler manner via
```
pip(3) install --user -r requirements.txt
```
